[package]
name = "sema"
version = "0.1.0"
edition = "2021"

[dependencies]
battery = "0.7.8"
regex-lite = "0.1.5"
gtk-layer-shell = "0.8.0"
gtk = "0.18.1"
gdk = "0.18.0"

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
